// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSrk8Y0Oz9JBOD-ivCXUc2KIohi1f2nSY',
    appId: '1:180964078388:web:8e6837ad64e7d8e6512b61',
    messagingSenderId: '180964078388',
    projectId: 'authreact-f8fe7',
    authDomain: 'authreact-f8fe7.firebaseapp.com',
    storageBucket: 'authreact-f8fe7.firebasestorage.app',
    measurementId: 'G-F72WXYW3XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU1acTa-yZxOGm3h0-WyUV5Kc1oQ50hhE',
    appId: '1:180964078388:android:4f8c3f78c33737cc512b61',
    messagingSenderId: '180964078388',
    projectId: 'authreact-f8fe7',
    storageBucket: 'authreact-f8fe7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqW_ckRIidfBy6l8W-o_rSY88ywa0LYqQ',
    appId: '1:180964078388:ios:664adabb44ee9bc2512b61',
    messagingSenderId: '180964078388',
    projectId: 'authreact-f8fe7',
    storageBucket: 'authreact-f8fe7.firebasestorage.app',
    iosBundleId: 'com.hid33nstudios.stock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqW_ckRIidfBy6l8W-o_rSY88ywa0LYqQ',
    appId: '1:180964078388:ios:664adabb44ee9bc2512b61',
    messagingSenderId: '180964078388',
    projectId: 'authreact-f8fe7',
    storageBucket: 'authreact-f8fe7.firebasestorage.app',
    iosBundleId: 'com.hid33nstudios.stock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSrk8Y0Oz9JBOD-ivCXUc2KIohi1f2nSY',
    appId: '1:180964078388:web:f5e5ec4b418dc77e512b61',
    messagingSenderId: '180964078388',
    projectId: 'authreact-f8fe7',
    authDomain: 'authreact-f8fe7.firebaseapp.com',
    storageBucket: 'authreact-f8fe7.firebasestorage.app',
    measurementId: 'G-3LMKDNGEFD',
  );
}
